// gestionnaire_de_stage_frontend/src/components/Manager/ValidateOffer/ValidateOffer.jsx
import React, {useState} from 'react';
import PreviewOffer from "../../PreviewOffer/PreviewOffer";
import OfferService from '../../../services/offer-service';
import {swalErr} from "../../../utility";
import Swal from "sweetalert2";
import "./ValidateOffer.css";

export default function ValidateOffer({offer}) {
    const [valid, setValid] = useState(false);
    const service = OfferService

    const validateOffer = (offer, isValid) => {
        offer.valid = isValid;
        service.validateOffer(offer)
            .then(v => {
                if (typeof v === "string") {
                    console.error(v);
                    swalErr(v).fire({}).then();
                    return;
                }
                setValid(isValid)
                let title = isValid ? 'Offre validée!' : 'Offre invalidée!'
                Swal.fire({title: title, icon: 'success'}).then();
            })
            .catch(e => {
                console.error(e)
                swalErr(e).fire({}).then();
            });

    }


    return <div className={`${valid ? 'border-left border-success' : 'border-left border-danger'}`}>
        <PreviewOffer offer={offer}/>
        <div className="d-flex justify-content-between align-items-center">
            <button id="validateBtn" className="btn btn-success fw-bold text-white w-50"
                    onClick={() => validateOffer(offer, true)}>Valide
            </button>
            <button id="invalidateBtn" className="btn btn-danger fw-bold text-white w-50"
                    onClick={() => validateOffer(offer, false)}>Invalide
            </button>
        </div>
    </div>
}

// vue_frontend/src/views/Offer/ValidateOffer.vue
<template>
  <div class="border-left bg-dark rounded" v-bind:class="{'border-success': this.valid, 'border-danger': !this.valid }">
    <PreviewOffer :offer="this.offer"/>
    <div class="d-flex justify-content-between align-items-center">
      <button id="validateBtn" class="btn btn-success fw-bold text-white w-50"
              v-on:click="this.validateOffer(this.offer, true)">Valide
      </button>
      <button id="invalidateBtn" class="btn btn-danger fw-bold text-white w-50"
              v-on:click="this.validateOffer(this.offer, false)">Invalide
      </button>
    </div>
  </div>
</template>

<script>
import Offer from '../../models/Offer';
import offerService from "../../services/offer-service";
import Swal from "sweetalert2";
import PreviewOffer from './PreviewOffer';

export default {
  name: "ValidateOffer",
  props: {
    offer: Offer
  },
  data() {
    return {
      valid: false
    }
  },
  components: {
    PreviewOffer
  },
  methods: {
    validateOffer(offer, valid) {
      offer.valid = valid;
      offerService.validateOffer(this.offer).then(response => {
        if (response.message) {
          console.trace(response.message);
          Swal.fire({
            title: response.message,
            icon: 'error'
          });
          return;
        }

        this.valid = valid;
        Swal.fire(valid ? 'Offre validée!' : 'Offre invalidée!', '', valid ? 'success' : 'error').then();

        this.$destroy()
        this.$el.parentNode.removeChild(this.$el);
      });
    }
  }
}
</script>

<style scoped>

</style>
