// vue_frontend/src/components/ValidateOffer.vue
<template>
  <div class="border-left"  v-bind:class="{'border-success': this.valid, 'border-danger': !this.valid }">
    <PreviewOffer :offer=this.offer />
    <div class="d-flex justify-content-between align-items-center">
      <button id="validateBtn" class="btn btn-success fw-bold text-white w-50"
              v-on:click="this.validateOffer(this.offer, true)">Valide</button>
      <button id="invalidateBtn" class="btn btn-danger fw-bold text-white w-50"
              v-on:click="this.validateOffer(this.offer, false)">Invalide</button>
    </div>
  </div>
</template>

<script>
import Offer from '../models/offer';
import offerService from "../services/offer-service";
import Swal from "sweetalert2";

export default {
  name: "ValidateOffer",
  props:{
    offer: Offer
  },
  data(){
    return {
      valid: false
    }
  },
  methods: {
    validateOffer: (offer, valid) => {
      offer.valid = valid;
      offerService.validateOffer(this.offer).then(response => {
          if(response.message){
            console.trace(response.message);
            Swal.fire({
              title: response.message,
              icon: 'error'
            });
            return;
          }

        this.valid = valid;
        Swal.fire(valid ? 'Offre validée!' : 'Offre invalidée!', '', valid ? 'success': 'error').then();
      });
    }
  }
}
</script>

<style scoped>

</style>

// gestionnaire_de_stage_frontend/src/components/ValidateOffer/ValidateOffer.jsx
import React, {Component} from 'react';
import PreviewOffer from "../PreviewOffer/PreviewOffer";
import OfferService from '../../services/offer-service';
import {swalErr} from "../../utility";
import Swal from "sweetalert2";
import "./ValidateOffer.css";

export default class ValidateOffer extends Component{
    constructor(props) {
        super(props);
        this.state = {
            valid: false
        }
        this.service = OfferService
    }

    validateOffer = (offer, valid) => {
        offer.valid = valid;
        this.service.validateOffer(offer)
            .then(v => {
                if(typeof v === "string") {
                    console.trace(v);
                    swalErr(v).fire({}).then();
                    return;
                }
                this.setState({valid})
                Swal.fire(valid ? 'Offre validé!' : 'Offre invalidé!', '', valid ? 'success': 'error').then();
            })
            .catch(e => {
                console.trace(e)
                swalErr(e).fire({}).then();
            });
    }

    render() {
        const {offer} = this.props;
        const {valid} = this.state;

        return <div className={`${valid ? 'border-left border-success' : 'border-left border-danger'}`}>
                {PreviewOffer(offer)}
                <div className="d-flex justify-content-between align-items-center">
                    <button id="validateBtn" className="btn btn-success fw-bold text-white w-50"
                            onClick={() => this.validateOffer(offer, true)}>Valide</button>
                    <button id="invalidateBtn" className="btn btn-danger fw-bold text-white w-50"
                            onClick={() => this.validateOffer(offer, false)}>Invalide</button>
                </div>
            </div>
    }
}
