// vue_frontend/src/components/ReviewOffers.vue
<template>
  <div class="container">
    <ul>
      <li v-for="(offer, index) in offers" :key="index">
        <ValidateOffer :offer="offer" />
      </li>
    </ul>
  </div>
</template>
<script>
import offerService from "../services/offer-service";
import Swal from "sweetalert2";

export default {
  name: "ReviewOffers",
  data() {
    return {
      offers: []
    }
  },
  created: function(){
    this.loadOffers();
  },
  methods: {
    loadOffers: function(){
      offerService.getAllOffers().then(offers => (this.offers = offers))
          .catch(e => {
            console.trace(e);
            Swal.fire({
              title: e,
              icon: 'error'
            });
          })
    },
  }
}
</script>

<style scoped>

</style>

// gestionnaire_de_stage_frontend/src/components/Manager/ReviewOffers/ReviewOffers.jsx
import './ReviewOffers.css'
import React, {useEffect, useState} from 'react';
import offerService from '../../../services/offer-service';
import ValidateOffer from "../ValidateOffer/ValidateOffer";
import {swalErr} from "../../../utility";

export default function ReviewOffers() {

    const [offers, setOffers] = useState([])
    useEffect(() => {
        offerService.getAllOffersInvalid()
            .then(offers => {
                setOffers(offers)
            })
            .catch(e => {
                setOffers([]);
                console.error(e);
                swalErr(e).fire({}).then();
            })
    }, [])


    return (
        <>
            <h1 className="text-center">Review Offers</h1>
            <div className='container'>
                <ul>
                    {offers.map((offer, index) => <li key={index}><ValidateOffer offer={offer}/></li>)}
                </ul>
            </div>
        </>
    );
}
