// vue_frontend/src/views/Offer/ReviewOffers.vue
<template>
  <div class="container">
    <ul class="list-inline">
      <li v-for="(offer, index) in offers" :key="index" class="mb-4">
        <ValidateOffer :offer="offer"/>
      </li>
    </ul>
  </div>
</template>
<script>

import offerService from "../../services/offer-service";
import Swal from "sweetalert2";
import ValidateOffer from "./ValidateOffer";

export default {
  name: "ReviewOffers",
  data() {
    return {
      offers: []
    }
  },
  components: {
    ValidateOffer
  },
  created() {
    this.loadOffers();
  },
  methods: {
    loadOffers() {
      offerService.getAllOffersNotValid().then(offers => (this.offers = offers))
          .catch(e => {
            console.trace(e);
            Swal.fire({
              title: e,
              icon: 'error'
            });
          })
    },
  }
}
</script>

<style scoped>

</style>

// gestionnaire_de_stage_frontend/src/components/Manager/ReviewOffers/ReviewOffers.jsx
import './ReviewOffers.css'
import React, {useEffect, useState} from 'react';
import offerService from '../../../services/offer-service';
import ValidateOffer from "../ValidateOffer/ValidateOffer";
import {swalErr} from "../../../utility";

export default function ReviewOffers() {

    const [offers, setOffers] = useState([])
    useEffect(() => {
        offerService.getAllOffersInvalid()
            .then(offers => {
                setOffers(offers)
            })
            .catch(e => {
                setOffers([]);
                console.error(e);
                swalErr(e).fire({}).then();
            })
    }, [])


    return (
        <>
            <h1 className="text-center">Review Offers</h1>
            <div className='container'>
                <ul>
                    {offers.map((offer, index) => <li key={index}><ValidateOffer offer={offer}/></li>)}
                </ul>
            </div>
        </>
    );
}
