// gestionnaire_de_stage_frontend/src/components/Contract/ContractSigned.jsx
import PdfDocumentViewer from "../SharedComponents/PdfDocumentViewer/PdfDocumentViewer";
import {useEffect, useState} from "react";
import {toPdfBlob} from "../../../../vue_frontend/src/services/utility";

export default function ContractSigned({contract}) {
    const [pdf, setPdf] = useState(null);

    useEffect(() => setPdf(toPdfBlob(contract.contractPDF)), [contract.contractPDF]);

    const studentFullName = student => `${student.firstName} ${student.lastName}`;

    return <div className='d-flex align-items-center justify-content-center flex-column'>
        <h2>Contrat de {studentFullName(contract.student)}</h2>

        <PdfDocumentViewer showContract={true} file={pdf}
                           fileName={`contrat_${studentFullName(contract.student)}.pdf`}/>
    </div>
}

// vue_frontend/src/views/Contract/ContractSigned.vue
<template>
  <div className='d-flex align-items-center justify-content-center flex-column'>
    <h2>Contrat de {{ studentFullName(contract.student) }}</h2>
    <div v-if="this.pdf">
      <pdf :src="this.url"></pdf>
    </div>
  </div>
</template>

<script>
import {toPdfBlob} from "@/services/utility";

export default {
  name: "ContractSigned",
  data() {
    return {
      pdf: null,
      url: null
    };
  },
  props: {
    contract: {
      type: Object,
      required: true
    }
  },
  created() {
    this.pdf = toPdfBlob(contract.contractPDF);
    this.url = window.URL.createObjectURL(this.pdf);
    window.URL.revokeObjectURL(this.url);
  },
  methods: {
    studentFullName(student) {
      return `${student.firstName} ${student.lastName}`;
    }
  }
}
</script>

<style scoped>

</style>
