// vue_frontend/src/views/StepCegep.vue
<template>
<div>
  <div class="form-group row">
    <div class="col-md-12">
      <label>Matricule</label>
      <div class="input-group">
        <input name="matricule" placeholder="Matricule" class="form-control" type="number"
               :value="matricule" v-on:change="this.handleChange('matricule')"/>
      </div>
    </div>
  </div>
  <div class="form-group text-center">
    <label/>
    <div>
      <button class="btn btn-primary" type="button" v-on:click="this.previous">Précédent</button>
      <button class="btn btn-primary" type="button" v-on:click="this.continue(Step.GENERAL)">Suivant</button>
    </div>
  </div>
</div>
  )
</template>

<script>
import {UserType} from "../models/RegisterVars";

export default {
  name: "StepCegep",
  props:{
    prevStep: Function,
    nextStep: Function,
    updateUserType: Function,
    handleChange: Function,
    matricule: String
  },
  data(){
    return {
      previous(e){
        e.preventDefault()
        this.prevStep();
      },
      continue(val){
        if (this.matricule.length === 5)
          this.updateUserType(UserType.SUPERVISOR)
        if (this.matricule.length === 7)
          this.props.updateUserType(UserType.STUDENT)
        this.nextStep(val);
      }

    }
  }
}
</script>

<style scoped>

</style>

// gestionnaire_de_stage_frontend/src/components/Register/Steps/StepCegep.jsx
import {Step, UserType} from "../Register";
import {Component} from "react";

export default class StepCegep extends Component {

    previous = (e) => {
        e.preventDefault()
        this.props.prevStep();
    }

    continue = (val) => {
        const {matricule} = this.props

        if (matricule.length === 5)
            this.props.updateUserType(UserType.SUPERVISOR)
        if (matricule.length === 7)
            this.props.updateUserType(UserType.STUDENT)
        this.props.nextStep(val);
    }

    render() {
        const matricule = this.props.matricule
        return (<div>
                <div className="form-group row">
                    <div className="col-md-12">
                        <label>Matricule</label>
                        <div className="input-group">
                            <input name="matricule" placeholder="Matricule" className="form-control" type="number"
                                   value={matricule} onChange={this.props.handleChange('matricule')}/>
                        </div>
                    </div>
                </div>
                <div className="form-group text-center">
                    <label/>
                    <div>
                        <button className="btn btn-primary" type={"button"} onClick={this.previous}>Precedent</button>
                        <button className="btn btn-primary" type={"button"} onClick={() => {
                            this.continue(Step.GENERAL)
                        }}>Suivant
                        </button>
                    </div>
                </div>
            </div>
        )
    }
}
