// gestionnaire_de_stage_frontend/src/components/Login/Login.jsx
import './Login.css'
import React, {useState} from "react";
import {UserType} from "../Register/Register";
import AuthService from "../../services/auth-service";
import FieldPassword from "../Fields/FieldPassword";
import FieldEmail from "../Fields/FieldEmail";


export default function Login(props) {

    const service = AuthService
    const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')
    const [userType, setUserType] = useState(UserType.MONITOR[0])

    const connect = (e) => {
        e.preventDefault()
        service.signIn(userType, email, password).then(() => {
            if (service.isAuthenticated())
                props.history.push('/')
        })
    }


    return (<>
            <div className="container bg-dark px-3 py-4 rounded shadow-lg mt-5">
                <h2 className="text-center">Se connecter</h2>
                <div className="form-group">
                    <label>Type d'utilisateur</label>
                    <div className="input-group">
                        <select className="form-control" name="choice" id="userTypes"
                                onChange={(e)=>setUserType(e.target.value)}>
                            <option defaultChecked={true} value={UserType.MONITOR[0]}>{UserType.MONITOR[1]}</option>
                            <option value={UserType.SUPERVISOR[0]}>{UserType.SUPERVISOR[1]}</option>
                            <option value={UserType.STUDENT[0]}>{UserType.STUDENT[1]}</option>
                            <option value={UserType.MANAGER[0]}>{UserType.MANAGER[1]}</option>
                        </select>
                    </div>
                </div>
                <div className="form-group row">
                    <div className="col-md-6">
                        <FieldEmail email={email} label="Email" placeholder="Votre Email"
                                    handleChanges={(e)=>setEmail(e.target.value)}/>
                    </div>
                    <div className="col-md-6">
                        <FieldPassword password={password} label="Mot de passe"
                                       placeholder="Votre mot de passe"
                                       handleChange={(e)=>setPassword(e.target.value)}/>
                    </div>
                </div>
                <div className="form-group text-center">
                    <label/>
                    <button className="btn btn-primary" type={"button"} onClick={connect}>Connexion</button>
                </div>
            </div>
        </>
    )
}

// vue_frontend/src/views/Authentication/Login.vue
<template>
  <div class="container">
    <form action="" class="bg-dark p-4 rounded" @submit.prevent="login">
      <div class="form-group">
        <label>Type d'utilisateur</label>
        <select v-model="userType" class="form-select">
          <option disabled selected>Choissisez un type d'utilisateur</option>
          <option>monitor</option>
          <option>student</option>
          <option>supervisor</option>
          <option>manager</option>
        </select>
      </div>
      <div class="form-group mt-2">
        <label for="email">Email</label>
        <input id="email" v-model="email" class="form-control" type="email">
      </div>
      <div class="form-group mt-2">
        <label for="password">Password</label>
        <input id="password" v-model="password" class="form-control" type="password">
      </div>
      <button class="btn bg-primary btn-primary mt-4 rounded w-100 fw-bold" type="submit" @click.prevent="login">Login
      </button>
    </form>
  </div>
</template>

<script>
import AuthService from '../../services/auth-service';
import Swal from "sweetalert2";

export default {
  name: "Login",
  data() {
    return {
      email: "",
      password: "",
      userType: "",
      service: AuthService,
    };
  },
  methods: {
    login() {
      let allFieldsFilled = true;
      for (const prop in this) {
        if (prop === '' || this[prop] === '' || this[prop] === null) {
          Swal.fire({
            title: 'Oops...',
            text: 'Veuillez remplir tous les champs',
            icon: 'error'
          });
          allFieldsFilled = false;
          break;
        }
      }
      if (allFieldsFilled)
        this.service.signIn(this.userType, this.email, this.password);
    }
  }
}
</script>

<style scoped>

</style>
