// vue_frontend/src/views/ContractToSignStudent.vue
<template>
  <ContratSignature :contract="contract" :userType="'student'"/>
</template>
<script>
import authService from "@/services/auth-service";
import {getContractForStudent} from "@/services/contrat-service";
import ContractSignature from "@/views/ContractSignature";

export default {
  name: "ContractToSignStudent",
  data(){
    return {
      contract: null,
      id: null
    };
  },
  components: ContractSignature,
  created() {
    this.id = authService.getUserId();
    getContractForStudent(this.id).then(contract => {
      this.contract = contract;
    });
  }
}
</script>

<style scoped>

</style>

// gestionnaire_de_stage_frontend/src/components/Contract/ContractToSignStudent.jsx
import ContratSignature from "./ContratSignature";
import {useAuth} from "../../services/use-auth";
import {useEffect, useState} from "react";
import {getContractForStudent} from '../../services/contrat-service';
import {UserType} from "../../enums/UserTypes";
import MessageNothingToShow from "../SharedComponents/MessageNothingToShow/MessageNothingToShow";

export function ContractToSignStudent() {
    const auth = useAuth();
    const [contract, setContract] = useState(null);

    useEffect(() => {
        getContractForStudent(auth.user.id).then(contract => setContract(contract));
    }, [auth.user.id]);


    if (!contract)
        return <MessageNothingToShow message="Vous avez aucun contrat à signer en ce moment."/>

    return <ContratSignature contract={contract} userType={UserType.STUDENT[0]}/>

}
