// vue_frontend/src/views/Contract/ContractsToSign.vue
<template>
  <div v-if="contracts.length > 0">
    <ul>
      <li v-for="(child, index) in contracts" :key="index">
        <ContractSignature :contract="child" :userType="userType"
                           v-on:remove="removeContract(index)"/>
      </li>
    </ul>
  </div>
  <div v-else class="container">
    <div class="alert alert-info text-center">
      <h3>Aucun contrat à signer!</h3>
    </div>
  </div>
</template>
<script>
import {UserType} from "@/models/RegisterVars";
import {getAllContractsToBeSignedForMonitor, getAllContractsToBeStarted} from "@/services/contrat-service";
import authService from "@/services/auth-service";
import ContractSignature from "@/views/Contract/ContractSignature";

export default {
  name: "ContractsToSign",
  data() {
    return {
      contracts: [],
      id: null
    }
  },
  props: {
    userType: {
      type: String,
      required: true
    }
  },
  methods: {
    removeContract(contractId) {
      this.contracts = this.contracts.filter(contract => contract.id !== contractId);
    }
  },
  components: {ContractSignature},
  created() {
    this.id = authService.getUserId();
    if (this.userType === UserType.MANAGER[0])
      getAllContractsToBeStarted().then(contracts => (this.contracts = contracts));
    if (this.userType === UserType.MONITOR[0])
      getAllContractsToBeSignedForMonitor(this.id).then(contracts => (this.contracts = contracts));
  }
}
</script>

<style scoped>

</style>

// gestionnaire_de_stage_frontend/src/components/Contract/ContractsToSign.jsx
import React, {useEffect, useState} from "react";
import ContractSignature from "./ContratSignature";
import {getAllContractsToBeSignedForMonitor, getAllContractsToBeStarted} from "../../services/contrat-service";
import {UserType} from "../../enums/UserTypes";
import {useAuth} from "../../services/use-auth";
import MessageNothingToShow from "../SharedComponents/MessageNothingToShow/MessageNothingToShow";

export default function ContractsToSign({userType}) {
    const [contracts, setContracts] = useState([]);
    const auth = useAuth();

    useEffect(() => {
        if (userType === UserType.MANAGER[0])
            getAllContractsToBeStarted().then(contracts => setContracts(contracts));
        if (userType === UserType.MONITOR[0])
            getAllContractsToBeSignedForMonitor(auth.user.id).then(contracts => setContracts(contracts))
    }, [auth.user.id, userType]);

    const removeContract = (contractId) => {
        setContracts(prev => prev.filter(contract => contract.id !== contractId));
    };

    if (contracts.length === 0)
        return <MessageNothingToShow message="Aucun contrat à signer pour le moment..."/>


    return contracts.map((contract, index) =>
        <ContractSignature key={index} removeContract={removeContract} userType={userType}
                           contract={contract}/>)
}
