// gestionnaire_de_stage_frontend/src/components/PreviewStudent/PreviewStudent.jsx
import './PreviewStudent.css';
import {toast} from "../../utility";
import PreviewOffer from "../PreviewOffer/PreviewOffer";
import {AiOutlineFile} from "react-icons/all";

export default function PreviewStudent({dto}) {

    const openFile = () => {
        const decodedChars = atob(dto.file);
        const byteNums = new Array(decodedChars.length);
        for (let i = 0; i < decodedChars.length; i++)
            byteNums[i] = decodedChars.charCodeAt(i);
        let contentType = 'application/pdf';

        if (dto.fileName.endsWith('docx'))
            contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';

        const blob = new Blob([new Uint8Array(byteNums), {type: contentType}]);

        let url = window.URL.createObjectURL(blob);

        const a = document.createElement('a')
        a.href = url
        a.download = dto.fileName;
        a.click();
        URL.revokeObjectURL(url)
        toast.fire({title: 'Téléchargé'}).then()
    }

    return <div className=" p-3 mt-5 border-left border-right border-light">
        <div className={'row'}>
            <div className="col-12 col-sm-6">
                <div className={'d-flex justify-content-center align-items-center flex-column p-3 shadow h-100'}>
                    <h4 className={'p-2 rounded bg-secondary fw-bold text-white'}>{dto.firstName + ', ' + dto.lastName} </h4>
                    <div className={'d-flex justify-content-center align-items-center badge bg-primary text-wrap h2'}>
                        <AiOutlineFile/>
                        <button onClick={openFile} className={'ms-2 text-white'}>{dto.fileName}</button>
                    </div>
                </div>
            </div>
            <div className="col-12 col-sm-6">
                <PreviewOffer offer={dto.offerDTO}/>
            </div>
        </div>
    </div>
}

// vue_frontend/src/views/PreviewStudent.vue
<template>
  <div class=" p-3 mt-5 border-left border-right border-light">
    <div class="row">
      <div class="col-12 col-sm-6">
        <div class="d-flex justify-content-center align-items-center flex-column p-3 shadow h-100">
          <h4 class="p-2 rounded bg-secondary fw-bold text-white">{{ `${dto.firstName}, ${dto.lastName}` }} </h4>
          <div class="d-flex justify-content-center align-items-center badge bg-primary text-wrap h2">
            <a v-on:click="openFile" target="_blank" class="ms-2 text-white">{{ dto.fileName }}</a>
          </div>
        </div>
      </div>
      <div class="col-12 col-sm-6">
        <PreviewOffer v-bind:offer="dto.offerDTO" />
      </div>
    </div>
  </div>
</template>

<script>
import CurriculumDto from "@/models/CurriculumDto";
import PreviewOffer from "@/views/PreviewOffer";
export default {
  name: "PreviewStudent",
  props: {
    dto: {
      type: CurriculumDto
    }
  },
  components:{
    PreviewOffer
  },
  methods: {
    openFile() {
      const decodedChars = atob(this.dto.file);
      const byteNums = new Array(decodedChars.length);
      for (let i = 0; i < decodedChars.length; i++)
        byteNums[i] = decodedChars.charCodeAt(i);
      let contentType = 'application/pdf';

      if (this.dto.fileName.endsWith('docx'))
        contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';

      const blob = new Blob([new Uint8Array(byteNums), {type: contentType}]);

      let url = window.URL.createObjectURL(blob);

      const a = document.createElement('a')
      a.href = url
      a.download = this.dto.fileName;
      a.click();
      URL.revokeObjectURL(url)
      alert('téléchargé')
    }
  }
}
</script>

<style scoped>

</style>
