// gestionnaire_de_stage_frontend/src/components/Unauthenticated/Register/RegisterMonitor.jsx
import React, {useState} from "react";
import StepPassword from "./SharedSteps/StepPassword";
import StepInformationGeneral from "./SharedSteps/StepInformationGeneral";
import {MonitorModel} from "../../../models/User";
import {useHistory} from "react-router-dom";
import {useAuth} from "../../../services/use-auth";
import {FormGroup} from "../../SharedComponents/FormGroup/FormGroup";
import {BtnBack} from "../../SharedComponents/BtnBack";
import {useForm} from "react-hook-form";
import {regexCodePostal, regexName} from "../../../utility";
import {FormInput} from "../../SharedComponents/FormInput/FormInput";


export default function RegisterMonitor() {
    const {register, handleSubmit, watch, formState: {errors}} = useForm();
    let history = useHistory();
    let auth = useAuth();
    const [curentStep, setCurentStep] = useState(0)
    let show;


    const endThis = (email, password, lastName, firstName, phone, companyName, address, city, postalCode) => {
        let user = new MonitorModel(email, password, lastName, firstName, phone, companyName, address, city, postalCode);
        auth.signupMonitor(user).then(() => history.push("/login"))
    }

    const submit = (data, e) => {
        e.preventDefault();
        // noinspection JSUnresolvedVariable
        let submitter = e.nativeEvent.submitter.value
        const {
            firstName,
            lastName,
            email,
            password,
            confirmation,
            phone,
            address,
            city,
            postalCode,
            companyName
        } = data;
        if (submitter === 'Suivant') {
            if (curentStep === 0)
                setCurentStep(1)
            else if (curentStep === 1)
                setCurentStep(2)
            else if (curentStep === 2 && password === confirmation)
                endThis(email, password, lastName, firstName, phone, companyName, address, city, postalCode);
        } else if (submitter === 'Précédent')
            setCurentStep(curentStep - 1)
    };


    if (curentStep === 0)
        show = <StepMonitor register={register} errors={errors} watch={watch}/>
    else if (curentStep === 1)
        show = <StepInformationGeneral register={register} errors={errors} watch={watch}
                                       prev={() => setCurentStep(curentStep - 1)}/>
    else if (curentStep === 2)
        show =
            <StepPassword register={register} errors={errors} watch={watch} prev={() => setCurentStep(curentStep - 1)}/>


    return (<>
        <form className="form-container" onSubmit={handleSubmit(submit)}>
            <fieldset>
                {show}
            </fieldset>
        </form>
    </>);
}


function StepMonitor({register, errors}) {
    return (<>
        <FormGroup>
            <FormInput label="Nom de la compagnie" validation={{require: true, pattern: regexName}}
                       error={errors.companyName} name="companyName" register={register} type="text"
                       placeholder="Nom de compagnie"/>
            <FormInput label="Ville" validation={{required: true, pattern: regexName}} error={errors.city} name="city"
                       register={register} type="text" placeholder="Ville"/>
        </FormGroup>
        <FormGroup>
            <FormInput label="Adresse" validation={{required: true, pattern: regexName}} error={errors.address}
                       name="address" register={register} type="text" placeholder="Rue, boulevard, avenue.."/>
        </FormGroup>
        <FormGroup>
            <FormInput label="Code postal" validation={{required: true, pattern: regexCodePostal}}
                       error={errors.postalCode} name="postalCode" register={register} type="text"
                       placeholder="H0H 0H0"/>
        </FormGroup>
        <div className="form-group text-center">
            <div className="btn-group">
                <BtnBack/>
                <input className="btn btn-primary" type="submit" name="next" value="Suivant"/>
            </div>
        </div>
    </>)

}

// vue_frontend/src/views/RegisterMonitor.vue
<template>
<form @submit.prevent="register">
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input type="text" class="form-control" id="firstName" v-model="firstName" placeholder="Enter first name">
  </div>
  <div class="form-group">
    <label for="lastName">Last Name</label>
    <input type="text" class="form-control" id="lastName" v-model="lastName" placeholder="Enter last name">
  </div>
  <div class="form-group">
    <label for="email">Email address</label>
    <input type="email" class="form-control" id="email" v-model="email" placeholder="Enter email">
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" class="form-control" id="password" v-model="password" placeholder="Password">
  </div>
  <div class="form-group">
    <label for="phone">Phone</label>
    <input type="text" class="form-control" id="phone" v-model="phone" placeholder="Phone">
  </div>
  <div class="form-group">
    <label for="address">Address</label>
    <input type="text" class="form-control" id="address" v-model="address" placeholder="Address">
  </div>
  <div class="form-group">
    <label for="city">City</label>
    <input type="text" class="form-control" id="city" v-model="city" placeholder="City">
  </div>
  <div class="form-group">
    <label>Departement</label>
    <select id="dep" v-model="department">
      <option>informatique</option>
      <option>Arts et cinéma</option>
    </select>
  </div>
  <div class="form-group">
    <label for="zip">Code postal</label>
    <input type="text" class="form-control" id="zip" v-model="postalCode" placeholder="Code postal">
  </div>
  <button type="submit" @click.prevent="register">Submit</button>
</form>
</template>

<script>
import authService from "@/services/auth-service";
import router from "@/router";
import {MonitorModel} from "@/models/User";

export default {
  name: "RegisterMonitor",
  data() {
    return {
      email:'',
      password :'',
      lastName :'',
      firstName :'',
      phone :'',
      address :'',
      city :'',
      postalCode : '',
      department : ''
    };
  },
  methods: {
    register() {
      let allFieldsFilled = true;
      Object.values(this.data).forEach(value => {
        if(value === ''){
          alert('Please fill all the fields');
          allFieldsFilled = false;
        }
      });

      let monitor = new MonitorModel(this.email, this.password, this.lastName, this.firstName, this.phone, this.address, this.city, this.postalCode, this.department);

      if(allFieldsFilled){
        authService.signupMonitor(monitor);
        router.push("/login");
      }

    }
  }
}
</script>

<style scoped>

</style>
