// gestionnaire_de_stage_frontend/src/components/Register/Register.jsx
import './Register.css'
import React, {Component} from "react";
import StepPassword from "./Steps/StepPassword";
import StepInformationGeneral from "./Steps/StepInformationGeneral";
import StepMonitor from "./Steps/StepMonitor";
import Choice from "./Steps/StepChoices";
import StepCegep from "./Steps/StepCegep";
import {MonitorModel, Student, Supervisor} from "../../models/User";
import AuthService from "../../services/auth-service"

export const Step = {
    CHOICE: "choice",
    CEGEP: "cegep",
    GENERAL: "general",
    MONITOR: "monitor",
    STUDENT: "student",
    PASSWORD: "password",
}
export const UserType = {
    MONITOR: ["monitor", "moniteur"],
    STUDENT: ["student", "etudiant"],
    SUPERVISOR: ["supervisor", "superviseur"],
    MANAGER: ["manager", "gestionnaire"]
}

export default class Register extends Component {

    constructor(props) {
        super(props);
        this.state = {
            hideFields: true,
            step: Step.CHOICE,
            previousStep: [],
            userType: null,
            matricule: '',
            email: '',
            password: '',
            lastName: '',
            firstName: '',
            phone: '',
            companyName: '',
            address: '',
            codePostal: '',
            city: '',
        }
        this.service = AuthService
        this.handleChange = this.handleChange.bind(this);
        this.goHome = this.goHome.bind(this)

    }


    prevStep = () => {
        const {previousStep} = this.state;
        this.setState({step: previousStep[previousStep.length - 1]});
        previousStep.pop()
    }

    nextStep = (val) => {
        const {previousStep} = this.state;
        const {step} = this.state;
        previousStep.push(step)
        this.setState({lastStep: previousStep});
        this.setState({step: val});
    }

    updateUserType = (type) => {
        this.setState({userType: type})
    }

    handleChange = input => e => {
        this.setState({[input]: e.target.value});
    }

    goHome = () => {
        // this.props.history.push('/')
    }

    finish = () => {
        const {
            email, password, firstName, lastName, phone, companyName, address, codePostal, city, matricule
        } = this.state;
        let user = null
        if (this.state.userType === UserType.STUDENT) {
            user = new Student(email, password, lastName, firstName, phone, matricule);
            this.service.signupStudent(user).then(value => {
                console.log(value)
                this.goHome()
            });
        }
        if (this.state.userType === UserType.SUPERVISOR) {
            user = new Supervisor(email, password, lastName, firstName, phone, matricule);
            this.service.signupSupervisor(user).then(value => {
                console.log(value)
                this.goHome()
            })
        }
        if (this.state.userType === UserType.MONITOR) {
            user = new MonitorModel(email, password, lastName, firstName, phone, companyName, address, city, codePostal);
            this.service.signupMonitor(user).then(value => {
                console.log(value)
                this.goHome()
            })
        }

    }


    render() {
        const {step} = this.state;
        const {
            email,
            password,
            firstName,
            lastName,
            city,
            phone,
            companyName,
            address,
            codePostal,
            matricule
        } = this.state;
        const valGeneral = {email, firstName, lastName, phone}
        const valMonitor = {companyName, city, address, codePostal}
        let show = null;

        switch (step) {
            case Step.CHOICE:
                show = <Choice prevStep={this.prevStep} nextStep={this.nextStep}/>
                break;
            case Step.CEGEP:
                show = <StepCegep prevStep={this.prevStep} nextStep={this.nextStep} updateUserType={this.updateUserType}
                                  handleChange={this.handleChange}
                                  matricule={matricule}/>
                break;
            case Step.MONITOR:
                show = <StepMonitor prevStep={this.prevStep} nextStep={this.nextStep} updateUserType={this.updateUserType}
                                    handleChange={this.handleChange}
                                    values={valMonitor}/>
                break;
            case Step.GENERAL:
                show = <StepInformationGeneral prevStep={this.prevStep} nextStep={this.nextStep}
                                               handleChange={this.handleChange}
                                               values={valGeneral}/>
                break;
            case Step.PASSWORD:
                show = <StepPassword prevStep={this.prevStep} finish={this.finish} handleChange={this.handleChange}
                                     password={password}/>

                break;
            default:
                break;
        }
        return (<div>
            <button className="btn btn-primary" onClick={() => {
                this.setState({hideFields: !this.state.hideFields})
            }}>Show/hide
            </button>
            <div hidden={this.state.hideFields}>
                email:{email}<br/>
                lastname:{lastName}<br/>
                firstname:{firstName}<br/>
                password:{password}<br/>
                city:{city}<br/>
                companyName:{companyName}<br/>
                phone:{phone}<br/>
                address:{address}<br/>
                codePostal:{codePostal}<br/>
            </div>
            <div className="form-container">
                <form className="bg-dark px-3 py-4 rounded shadow-lg mt-5" id="contact_form">
                    <fieldset>
                        <legend>
                            <center><h2>Inscription</h2></center>
                            <center><h3>{step}</h3></center>
                        </legend>
                        <br/>
                        {show}
                    </fieldset>
                </form>
                <button className="btn btn-primary" onClick={() => {
                    this.goHome()
                }}>go home
                </button>
            </div>
        </div>);
    }
}

// vue_frontend/src/views/Register.vue
<template>
  <div class="form-container">
    <form class="bg-dark px-3 py-4 rounded shadow-lg mt-5" id="contact_form">
      <fieldset>
        <legend>
          <h2 class="d-inline-block mx-auto text-center">Inscription</h2>
        </legend>
        <br/>
          <div v-if="step === this.steps.CEGEP">
            <StepCegep  :prevStep="prevStep" :nextStep="nextStep" :updateUserType="updateUserType"
                       :handleChange="handleChange"
                       :matricule="matricule"/>
          </div>
          <div v-else-if="step === this.steps.GENERAL">
            <StepInformationGeneral :prevStep="prevStep" :nextStep="nextStep"
                                    :handleChange="handleChange"
                                    :values="{email, firstName, lastName, phone}"/>
          </div>
        <div v-else-if="step === this.steps.MONITOR">
          <StepMonitor  :prevStep="prevStep" :nextStep="nextStep" :updateUserType="updateUserType"
                       :handleChange="handleChange"
                       :values="{companyName, city, address, codePostal}"/>
        </div>
        <div v-else-if="step === this.steps.PASSWORD">
          <StepPassword :prevStep="prevStep" :finish="finish" :handleChange="handleChange"
                        :password="password"/>
        </div>
        <div v-else-if="step === this.steps.CHOICE">
          <Choice :prevStep="prevStep" :nextStep="nextStep"/>
        </div>
      </fieldset>
    </form>
  </div>
</template>

<script>

import StepCegep from "./StepCegep";
import StepMonitor from "./StepMonitor";
import StepPassword from "./StepPassword";
import StepInformationGeneral from './StepInformationGeneral';
import Choice from './Choice';
import {Step, UserType} from "../models/RegisterVars";
import {MonitorModel, Student, Supervisor} from "../models/User";
import authService from "../services/auth-service";
import router from "../router";

export default {
  name: "Register",
  created(){
    this.steps = Step;
    this.UserType = UserType;
  },
  data() {
    return {
      steps: Step,
      UserType: UserType,
      service: authService,
      hideFields: true,
      step: Step.CHOICE,
      previousStep: [],
      userType: null,
      matricule: '',
      email: '',
      password: '',
      lastName: '',
      firstName: '',
      phone: '',
      companyName: '',
      address: '',
      codePostal: '',
      city: '',
      prevStep() {
        this.step = this.previousStep[this.previousStep.length - 1];
        this.previousStep.pop()
      },
      nextStep(val) {
        this.previousStep.push(this.step)
        this.lastStep = this.previousStep;
        this.step = val;
      },
      updateUserType(type) {
        this.userType = type;
      },
      handleChange(input, e) {
        this[input] = e.target.value;
      },
      finish() {
        const {
          email, password, firstName, lastName, phone, companyName, address, codePostal, city, matricule
        } = this;
        switch (this.userType) {
          case UserType.STUDENT:
            this.service.signupStudent(new Student(email, password, lastName, firstName, phone, matricule)).then(value => {
              console.log(value)
              router.push("login")
            });
            break;
          case UserType.MONITOR:
            this.service.signupMonitor(new MonitorModel(email, password, lastName, firstName, phone, companyName, address, city, codePostal)).then(value => {
              console.log(value)
              router.push("login")
            })
            break;
          case UserType.SUPERVISOR:
            this.service.signupSupervisor(new Supervisor(email, password, lastName, firstName, phone, matricule)).then(value => {
              console.log(value)
              router.push("login")
            })
            break;
        }
      }
    }
  },
  components: {
    StepCegep,
    StepMonitor,
    StepPassword,
    StepInformationGeneral,
    Choice
  }
}
</script>

<style scoped>
.form-container {
  display: flex;
  justify-content: center;
  align-items: center;
}

label {
  margin-top: 20px;
  margin-bottom: 10px;
}

button {
  margin-right: 10px;
}

</style>
