// gestionnaire_de_stage_frontend/src/components/Unauthenticated/Register/Register.jsx
import React, {useState} from "react";
import StepPassword from "./Steps/StepPassword";
import StepInformationGeneral from "./Steps/StepInformationGeneral";
import StepMonitor from "./Steps/StepMonitor";
import Choice from "./Steps/StepChoices";
import StepCegep from "./Steps/StepCegep";
import {MonitorModel, Student, Supervisor} from "../../../models/User";
import {Step} from "../../../enums/Steps";
import {useHistory} from "react-router-dom";
import {useAuth} from "../../../services/use-auth";
import {UserType} from "../../../enums/UserTypes";


export default function Register() {
    let history = useHistory();
    let auth = useAuth();
    const [step, setStep] = useState(Step.CHOICE)
    const [previousStep, setPrevStep] = useState([])
    const [userType, setUserType] = useState(null)
    const [userInfo, setUserInfo] = useState({
        matricule: '',
        firstName: '',
        lastName: '',
        email: '',
        password: '',
        phone: '',
        address: '',
        city: '',
        postalCode: '',
        companyName: '',
    })
    const {
        matricule,
        firstName,
        lastName,
        email,
        password,
        phone,
        address,
        city,
        postalCode,
        companyName
    } = userInfo;

    const prevStep = () => {
        setStep(previousStep[previousStep.length - 1]);
        setPrevStep(previousStep.filter(item => item !== previousStep[previousStep.length - 1]))
    }

    const nextStep = (val) => {
        previousStep.push(step)
        setPrevStep(previousStep);
        setStep(val);
    }

    const updateUserType = (type) => {
        setUserType(type)
    }

    const handleChange = (event) => {
        let value = event.target.value;
        let name = event.target.name;

        setUserInfo((prev) => {
            return {
                ...prev,
                [name]: value
            }
        })
    }

    const endThis = (e) => {
        e.preventDefault();
        let user = null
        if (userType === UserType.STUDENT) {
            user = new Student(email, password, lastName, firstName, phone, matricule);
            auth.signupStudent(user).then(() => history.push("/login"));
        }
        if (userType === UserType.SUPERVISOR) {
            user = new Supervisor(email, password, lastName, firstName, phone, matricule);
            auth.signupSupervisor(user).then(() => history.push("/login"))
        }
        if (userType === UserType.MONITOR) {
            user = new MonitorModel(email, password, lastName, firstName, phone, companyName, address, city, postalCode);
            auth.signupMonitor(user).then(() => history.push("/login"))
        }

    }


    let show = null;

    switch (step) {
        case Step.CHOICE:
            show = <Choice prevStep={prevStep} nextStep={nextStep}/>
            break;
        case Step.CEGEP:
            show = <StepCegep prevStep={prevStep} nextStep={nextStep} updateUserType={updateUserType}
                              handleChange={handleChange}
                              matricule={matricule}/>
            break;
        case Step.MONITOR:
            show =
                <StepMonitor prevStep={prevStep} nextStep={nextStep} updateUserType={updateUserType}
                             handleChange={handleChange}
                             address={address} postalCode={postalCode} city={city} companyName={companyName}/>
            break;
        case Step.GENERAL:
            show = <StepInformationGeneral prevStep={prevStep} nextStep={nextStep}
                                           handleChange={handleChange}
                                           email={email} firstName={firstName} lastName={lastName} phone={phone}/>
            break;
        case Step.PASSWORD:
            show = <StepPassword prevStep={prevStep} handleChange={handleChange}
                                 password={password}/>

            break;
        default:
            break;
    }
    return (<>
        <form className="form-container" onSubmit={endThis}>
            <fieldset>
                {show}
            </fieldset>
        </form>
    </>);
}

// vue_frontend/src/views/Register.vue
<template>
  <div class="form-container">
    <form class="bg-dark px-3 py-4 rounded shadow-lg mt-5" id="contact_form">
      <fieldset>
        <legend>
          <h2 class="d-inline-block mx-auto text-center">Inscription</h2>
        </legend>
        <br/>
          <div v-if="step === this.steps.CEGEP">
            <StepCegep  :prevStep="prevStep" :nextStep="nextStep" :updateUserType="updateUserType"
                       :handleChange="handleChange"
                       :matricule="matricule"/>
          </div>
          <div v-else-if="step === this.steps.GENERAL">
            <StepInformationGeneral :prevStep="prevStep" :nextStep="nextStep"
                                    :handleChange="handleChange"
                                    :values="{email, firstName, lastName, phone}"/>
          </div>
        <div v-else-if="step === this.steps.MONITOR">
          <StepMonitor  :prevStep="prevStep" :nextStep="nextStep" :updateUserType="updateUserType"
                       :handleChange="handleChange"
                       :values="{companyName, city, address, codePostal}"/>
        </div>
        <div v-else-if="step === this.steps.PASSWORD">
          <StepPassword :prevStep="prevStep" :finish="finish" :handleChange="handleChange"
                        :password="password"/>
        </div>
        <div v-else-if="step === this.steps.CHOICE">
          <Choice :prevStep="prevStep" :nextStep="nextStep"/>
        </div>
      </fieldset>
    </form>
  </div>
</template>

<script>

import StepCegep from "./StepCegep";
import StepMonitor from "./StepMonitor";
import StepPassword from "./StepPassword";
import StepInformationGeneral from './StepInformationGeneral';
import Choice from './Choice';
import {Step, UserType} from "../models/RegisterVars";
import {MonitorModel, Student, Supervisor} from "../models/User";
import authService from "../services/auth-service";
import router from "../router";

export default {
  name: "Register",
  created(){
    this.steps = Step;
    this.UserType = UserType;
  },
  data() {
    return {
      steps: Step,
      UserType: UserType,
      service: authService,
      hideFields: true,
      step: Step.CHOICE,
      previousStep: [],
      userType: null,
      matricule: '',
      email: '',
      password: '',
      lastName: '',
      firstName: '',
      phone: '',
      companyName: '',
      address: '',
      codePostal: '',
      city: '',
      prevStep() {
        this.step = this.previousStep[this.previousStep.length - 1];
        this.previousStep.pop()
      },
      nextStep(val) {
        this.previousStep.push(this.step)
        this.lastStep = this.previousStep;
        this.step = val;
      },
      updateUserType(type) {
        this.userType = type;
      },
      handleChange(input, e) {
        this[input] = e.target.value;
      },
      finish() {
        const {
          email, password, firstName, lastName, phone, companyName, address, codePostal, city, matricule
        } = this;
        switch (this.userType) {
          case UserType.STUDENT:
            this.service.signupStudent(new Student(email, password, lastName, firstName, phone, matricule)).then(value => {
              console.log(value)
              router.push("login")
            });
            break;
          case UserType.MONITOR:
            this.service.signupMonitor(new MonitorModel(email, password, lastName, firstName, phone, companyName, address, city, codePostal)).then(value => {
              console.log(value)
              router.push("login")
            })
            break;
          case UserType.SUPERVISOR:
            this.service.signupSupervisor(new Supervisor(email, password, lastName, firstName, phone, matricule)).then(value => {
              console.log(value)
              router.push("login")
            })
            break;
        }
      }
    }
  },
  components: {
    StepCegep,
    StepMonitor,
    StepPassword,
    StepInformationGeneral,
    Choice
  }
}
</script>

<style scoped>
.form-container {
  display: flex;
  justify-content: center;
  align-items: center;
}

label {
  margin-top: 20px;
  margin-bottom: 10px;
}

button {
  margin-right: 10px;
}

</style>
