// gestionnaire_de_stage_frontend/src/components/Unauthenticated/Register/Steps/StepCegep.jsx
import React from "react";
import {UserType} from "../../../../enums/UserTypes";
import {Step} from "../../../../enums/Steps";
import {toastErr} from "../../../../utility";
import {FormGroup} from "../../../SharedComponents/FormGroup/FormGroup";
import {FormField} from "../../../SharedComponents/FormField/FormField";

export default function StepCegep({prevStep, nextStep, updateUserType, handleChange, matricule}) {
    const next = (matricule, val) => {
        if (!matricule) {
            toastErr.fire({title: 'Matricule invalid!'}).then()
            return
        }
        if (matricule.toString().length === 5)
            updateUserType(UserType.SUPERVISOR)
        else if (matricule.toString().length === 7)
            updateUserType(UserType.STUDENT)

        nextStep(val);
    }

    return (<>
            <FormGroup>
                <FormField htmlFor="matricule">
                    <label>Matricule</label>
                    <input data-testid="input-matricule" name="matricule" placeholder="Matricule" type="number"
                           value={matricule} onChange={handleChange}/>
                </FormField>
            </FormGroup>
            <div className="form-group text-center">
                <label/>
                <div>
                    <button className="btn btn-primary" type={"button"} onClick={prevStep}>Précédent</button>
                    <button className="btn btn-primary" type={"button"} onClick={() => {
                        next(matricule, Step.GENERAL)
                    }}>Suivant
                    </button>
                </div>
            </div>
        </>
    )

}

// vue_frontend/src/views/StepCegep.vue
<template>
<div>
  <div class="form-group row">
    <div class="col-md-12">
      <label>Matricule</label>
      <div class="input-group">
        <input name="matricule" placeholder="Matricule" class="form-control" type="number"
               :value="matricule" v-on:change="this.handleChange('matricule')"/>
      </div>
    </div>
  </div>
  <div class="form-group text-center">
    <label/>
    <div>
      <button class="btn btn-primary" type="button" v-on:click="this.previous">Précédent</button>
      <button class="btn btn-primary" type="button" v-on:click="this.continue(Step.GENERAL)">Suivant</button>
    </div>
  </div>
</div>
  )
</template>

<script>
import {UserType} from "../models/RegisterVars";

export default {
  name: "StepCegep",
  props:{
    prevStep: Function,
    nextStep: Function,
    updateUserType: Function,
    handleChange: Function,
    matricule: String
  },
  data(){
    return {
      previous(e){
        e.preventDefault()
        this.prevStep();
      },
      continue(val){
        if (this.matricule.length === 5)
          this.updateUserType(UserType.SUPERVISOR)
        if (this.matricule.length === 7)
          this.props.updateUserType(UserType.STUDENT)
        this.nextStep(val);
      }

    }
  }
}
</script>

<style scoped>

</style>
