// gestionnaire_de_stage_frontend/src/components/ViewOffers/ViewOffers.jsx
import React from "react";
import './ViewOffers.css'
import OfferService from '../../services/offer-service'
import PreviewOffer from '../PreviewOffer/PreviewOffer';
import AuthService from '../../services/auth-service';
import OfferDTO from "../../models/OfferDTO";

export default class ViewOffers extends React.Component {

    constructor(props) {
        super(props);
        console.log(AuthService.user);
        this.state = {
            department: AuthService.user.department || 'Informatique',
            offers: []
        };
        OfferService.getAllOffersByDepartment(this.state.department)
            .then(offers => this.setState({offers}))
            .catch(e => {
                this.setState({offers: []})
                console.trace(e);
            });
    }




    render() {
        return (
            <div className='container'>
                <h2 className="text-center">Offres de Stage</h2>
                <ul>
                    {this.state.offers.map((offer, index) => <li key={index}><PreviewOffer offer={offer}/></li>)}
                </ul>
            </div>
        );
    }
}

// vue_frontend/src/views/ViewOffers.vue
<template>
  <div class="container">
    <ul class="list-inline">
      <li v-for="(offer, index) in offers" :key="index" class="mb-4">
        <div>
          <PreviewOffer :offer="offer"/>
          <button class="btn btn-success text-dark w-100 fw-bold" @click.prevent="apply(offer.id)">Appliquer</button>
        </div>
      </li>
    </ul>
  </div>
</template>

<script>
import PreviewOffer from "@/views/PreviewOffer";
import offerAppService from "@/services/offerAppService";
import authService from "@/services/auth-service";
import offerService from "@/services/offer-service";
import OfferApp from "@/models/OfferApp";
export default {
  name: "ViewOffers",
  components: {PreviewOffer},
  data(){
    return {
      offers: []
    }
  },
  created() {
    offerService.getAllOffersValid().then(offers => {
      this.offers = offers;
    });
  },
  methods: {
    apply(idOffer) {
      const idStudent = authService.getUserId();
      offerAppService.apply(new OfferApp(idOffer, idStudent)).then();
    }
  }
}
</script>

<style scoped>

</style>
