// vue_frontend/src/views/ViewOffers.vue
<template>
  <div class="container">
    <ul class="list-inline">
      <li v-for="(offer, index) in offers" :key="index" class="mb-4">
        <div>
          <PreviewOffer :offer="offer"/>
          <button class="btn btn-success text-dark w-100 fw-bold" @click.prevent="apply(offer.id)">Appliquer</button>
        </div>
      </li>
    </ul>
  </div>
</template>

<script>
import PreviewOffer from "@/views/PreviewOffer";
import offerAppService from "@/services/offerAppService";
import authService from "@/services/auth-service";
import offerService from "@/services/offer-service";
import OfferApp from "@/models/OfferApp";
export default {
  name: "ViewOffers",
  components: {PreviewOffer},
  data(){
    return {
      offers: []
    }
  },
  created() {
    offerService.getAllOffersValid().then(offers => {
      this.offers = offers;
    });
  },
  methods: {
    apply(idOffer) {
      const idStudent = authService.getUserId();
      offerAppService.apply(new OfferApp(idOffer, idStudent)).then();
    }
  }
}
</script>

<style scoped>

</style>

// gestionnaire_de_stage_frontend/src/components/Manager/ViewOffers/ViewOffers.jsx
import React, {useEffect, useState} from "react";
import './ViewOffers.css'
import OfferService from '../../../services/offer-service'
import PreviewOffer from '../../PreviewOffer/PreviewOffer';
import AuthService from '../../../services/auth-service';

export default function ViewOffers() {

    const [offers, setOffers] = useState([])
    useEffect(() => {
        OfferService.getAllOffersByDepartment(AuthService.user.department || 'informatique')
            .then(offers => {
                console.log(offers)

                setOffers(offers)
            })
            .catch(e => {
                setOffers([])
                console.error(e);
            });
    }, [])


    return (
        <div className='container'>
            <h2 className="text-center">Offres de Stage</h2>
            <ul>
                {offers.map((offer, index) => <li key={index}><PreviewOffer offer={offer}/></li>)}
            </ul>
        </div>
    )
}
