// vue_frontend/src/components/ViewAppliedStudents.vue
<template>
  <div>
    <div class="d-flex justify-content-center align-items-center">
      <h2 class="text-center">Applicants</h2>
      <h2 class="ms-2">
        <span class="badge bg-secondary">{{ students.length }}</span>
      </h2>
    </div>
    <div v-if="students.length > 0">
      <div v-for="(student, index) in students" :key="index">
        <PreviewStudent v-bind:student="student"/>
      </div>
    </div>
    <div v-else class="d-flex justify-content-center align-items-center">
      <p class="text-center border border-white rounded p-2 mt-3">Aucun applicant à voir pour le moment</p>
    </div>
  </div>
</template>

<script>


import offerAppService from "@/services/offerAppService";
import PreviewStudent from "@/components/PreviewStudent";

export default {
  name: "ViewAppliedStudents",
  data: function () {
    return {
      students: []
    }
  },
  props: {
    email: String
  },
  created() {
    offerAppService.getAllApplicants(this.email).then(students => (this.students = students));
  },
  components: {
    PreviewStudent
  }
}
</script>

<style scoped>

</style>

// gestionnaire_de_stage_frontend/src/components/ViewAppliedStudents/ViewAppliedStudents.jsx
import React, {useEffect, useState} from 'react';
import PreviewStudent from "../PreviewStudent/PreviewStudent";
import OfferAppService from '../../services/offerAppService';
import PropTypes from 'prop-types';
export default function ViewAppliedStudents(email) {

    const [students, setStudents] = useState([]);

    const loadAllData = () => async () => await OfferAppService.getAllApplicants(email).then(v => setStudents(v))

    useEffect(loadAllData(), []);

    ViewAppliedStudents.propTypes = {
        email: PropTypes.string.isRequired
    }

    return <div className=''>
        <div className={'d-flex justify-content-center align-items-center'}>
            <h2 className="text-center">Applicants</h2>
            <h2 className={'ms-2'}>
                <span className={`badge bg-secondary`}>{students.length}</span>
            </h2>
        </div>
            {students.length > 0 ?
                students.map((student, index) => <div key={index}>{PreviewStudent(student)}</div>)
             : (
                <div className={"d-flex justify-content-center align-items-center"}>
                    <p className={"text-center border border-white rounded p-2 mt-3"}>Aucun applicant à voir pour le moment</p>
                </div>
            )}
    </div>;
}
