// gestionnaire_de_stage_frontend/src/components/ReviewOffers/ReviewOffers.jsx
import './ReviewOffers.css'
import React, {Component} from 'react';
import OfferService from '../../services/offer-service';
import ValidateOffer from "../ValidateOffer/ValidateOffer";
import {swalErr} from "../../utility";

export default class ReviewOffers extends Component{

    constructor(props){
        super(props);
        this.service = OfferService;
        this.state = {
            offers: []
        }
        this.service.getAllOffers()
            .then(offers => this.setState({offers}))
            .catch(e => {
                console.trace(e);
                swalErr(e).fire({}).then();
            })
    }

    render() {
        const {offers} = this.state;
        return (
            <div className='container'>
                <ul>
                    {offers.map((offer, index) => <li key={index}><ValidateOffer offer={offer}/></li>)}
                </ul>
            </div>
        );
    }
}

// vue_frontend/src/components/ReviewOffers.vue
<template>
  <div class="container">
    <ul>
      <li v-for="(offer, index) in offers" :key="index">
        <ValidateOffer :offer="offer" />
      </li>
    </ul>
  </div>
</template>
<script>
import offerService from "../services/offer-service";
import Swal from "sweetalert2";

export default {
  name: "ReviewOffers",
  data() {
    return {
      offers: []
    }
  },
  created: function(){
    this.loadOffers();
  },
  methods: {
    loadOffers: function(){
      offerService.getAllOffers().then(offers => (this.offers = offers))
          .catch(e => {
            console.trace(e);
            Swal.fire({
              title: e,
              icon: 'error'
            });
          })
    },
  }
}
</script>

<style scoped>

</style>
